#%RAML 1.0
---
title: Making Tax Digital Income Tax Subscription
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include http://api-documentation-raml-frontend.service/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include http://api-documentation-raml-frontend.service/api-documentation/assets/common/docs/errors.md

mediaType: [ application/json, application/hal+json ]

uses:
  sec: http://api-documentation-raml-frontend.service/api-documentation/assets/common/modules/securitySchemes.raml
  headers: http://api-documentation-raml-frontend.service/api-documentation/assets/common/modules/headers.raml
  annotations: http://api-documentation-raml-frontend.service/api-documentation/assets/common/modules/annotations.raml
  types: http://api-documentation-raml-frontend.service/api-documentation/assets/common/modules/types.raml

/income-tax:
  /subscription:
    post:
      displayName: Post MTD Income Tax subscription
      description: |
        Allows a user to subscribe to the Making Tax Digital Income Tax service.

        It's a user-restricted endpoint which requires an OAuth 2.0 `access_token`.
      is: [headers.acceptHeader]
      (annotations.scope): "write:income-tax"
      securedBy: [ sec.oauth_2_0: { scopes: [ "write:income-tax" ] } ]
      body:
        application/json:
          schema: !include schemas/create-subscription-request.json
          examples:
            example-1:
              value: !include examples/create-subscription-request-1.json
      responses:
        201:
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                badRequest:
                  scenario: Bad Request
                  code: BAD_REQUEST
                badRequest2:
                  scenario: Invalid request payload
                  code: BAD_REQUEST
        401:
          body:
            application/json:
              type: types.errorResponse
              examples:
                unauthorized:
                  scenario: Unauthorized
                  code: UNAUTHORIZED
        404:
          body:
            application/json:
              type: types.errorResponse
              examples:
                notFound:
                  scenario: Resource Not Found
                  code: NOT_FOUND
        406:
          body:
            application/json:
              type: types.errorResponse
              examples:
                acceptHeader:
                  scenario: Accept Header Invalid
                  code: ACCEPT_HEADER_INVALID
                contentType:
                  scenario: Content-Type Header Invalid
                  code: CONTENT_TYPE_HEADER_INVALID
        500:
          body:
            application/json:
              type: types.errorResponse
              examples:
                internalError:
                  scenario: Internal Server Error
                  code: INTERNAL_SERVER_ERROR